name: Run tests

# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
# Run this workflow whenever the job above -run-tests- is sucessfully completed
  run-sh-file:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:

      - name: Run-sh-file
        run: echo "let's test"
#       run: mkdir vogel --> werkt maar doet niets net als copy origineel
#       run: mkdir ~/my-project/vogel --> mkdir: cannot create directory ‘/home/runner/my-project/vogel’: No such file or directory
#       run: nano vogel.txt  --> Error opening terminal: unknown.
#       run: echo $/my-project/new_farm/script-farm.sh
        shell: bash
