name: Run tests
description: "Run tests on new farm app and update"

# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
# Run this workflow whenever the job above -run-tests- is sucessfully completed
  run-sh-file:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Run-sh-file
        run: echo $/my-project/new_farm/script-farm.sh
        shell: bash
        with: SSH_PRIVATE_KEY: ${{secrets.THE_KEY}}
